version: '3'

services:
  api-solid-pg:
    image: bitnami/postgresql:15.5.0
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USERNAME=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DATABASE=apisolid