name: Run e2e Tests

on: [pull_request]

jobs: 
  run-unit-test:
    name: Run e2e Test
    runs-on: ubuntu-latest

    services:
      api-solid-pg:
        image: bitnami/postgresql:15.5.0
        ports:
          - "5432:5432"
        env:
          POSTGRES_USERNAME: test
          POSTGRES_PASSWORD: test
          POSTGRES_DATABASE: test    

    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8.12.1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install dependencies
        run: pnpm install

      - name: Database Migrate
        run: pnpm exec prisma migrate deploy
        env:
          DATABASE_URL: "postgresql://test:test@localhost:5432/test?schema=public"

      - run: pnpm test:e2e
        env:
          JWT_SECRET: testing
          DATABASE_URL: "postgresql://test:test@localhost:5432/test?schema=public"