name: Run Unit Tests

on: [push]

jobs: 
  run-unit-test:
    name: Run Unit Test
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          node-version: 20
          cache: pnpm
          
      - run: pnpm install
      - run: pnpm test